### ISSUE TITLE
Crash at first opening #2

### ISSUE THREAD

**Issue by ufgo** [defold/extension-push#26]
Defold 1.2.174
Push extension 2.0.1
Android Miui 11.05

When opening the app for the 1st time, I get the crash.
Last string in the dump:

`D/push-firebase: Refreshed token: ...`

**Comment by britzl** [comment]
Really? This is the exact error that happened before 2.0.1 and exactly what 2.0.1 was supposed to fix. Can you please double check that you are using version 2.0.1 of the extension in the version you are testing?

**Comment by ufgo** [comment]
> Really? This is the exact error that happened before 2.0.1 and exactly what 2.0.1 was supposed to fix. Can you please double check that you are using version 2.0.1 of the extension in the version you are testing?

Yes. I test more then two times and app crash after first run(

**Comment by britzl** [comment]
Ok, and when you updated to 2.0.1 by changing version in game.project did you also do an editor restart or Project->Fetch Libraries to also get the 2.0.1?

If you didn't you still build using 2.0.0 despite what it says in game.project.

**Comment by ufgo** [comment]
> Ok, and when you updated to 2.0.1 by changing version in game.project did you also do an editor restart or Project->Fetch Libraries to also get the 2.0.1?
> 
> If you didn't you still build using 2.0.0 despite what it says in game.project.

Yes of course

**Comment by britzl** [comment]
Ah, I see it now. We debated a last minute change to how the callback was destroyed, but decided to not make the change, which in fact now is causing a crash. I'm fixing it!
